# action.yml
name: 'Bootstrap Kotlin service'
description: 'Creates task definition and service startup configuration files'
inputs:
    run_cmd:
        description: 'Command used to start the service application'
        required: true
    task_memory: 
        description: 'Amount of memory (in MB) ECS will allocate to the service task'
        required: true
    service_name:
        description: "Name of the service"
        required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        RUN_CMD: ${{ inputs.run_cmd }}
        TASK_MEMORY: ${{ inputs.task_memory }}
        SERVICE: ${{ inputs.service_name }}
    args:
        - ${{ inputs.service_name }}
